services:
  server:
    container_name: server
    build:
      context: .
    networks:
      - my_network
    environment:
      NODE_ENV: production
      PRIVATE_KEY: super_private_key#
      DB_URI: mongodb://localhost:27017/ecommerce?authSource=admin
      PORT: 9000
      API_URI: http://5.189.158.182:9000
      DB_USER: root
      DB_PASSWORD: brightkyefoo
    ports:
      - 9000:9000
    depends_on:
      - mongo_server

  mongo_server:
    container_name: mongo_server
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: brightkyefoo
    ports:
      - 27017:27017
    networks:
      - my_network

networks:
  my_network:
    driver: bridge